# MongoDB
mongo_uri = "mongodb://localhost:27017/"
mongo_db = "stocks_db"

# PostgreSQL
pg_user = "postgres"
pg_password = "adomagala"
pg_host = "localhost"
pg_port = 5432
pg_db = "trading_analyzer"

# Supabase
sb_url = "https://pyzvscajljdejorlyzef.supabase.co"
sb_api = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5enZzY2FqbGpkZWpvcmx5emVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MjEyODksImV4cCI6MjA3NTA5NzI4OX0.MeFsXBnfryXwUIAudKrc1AcEmNC9xJUo0hCWGePW1Oc"
sb_password = "Adrian9875GetMeAWork"
