def human_readable_market_cap(value):
    """Konwertuje market cap na czytelny format: K, M, B, T"""
    try:
        value = float(value)
    except:
        return value

    if value >= 1_000_000_000_000:
        return f"{value / 1_000_000_000_000:.2f}T"
    elif value >= 1_000_000_000:
        return f"{value / 1_000_000_000:.2f}B"
    elif value >= 1_000_000:
        return f"{value / 1_000_000:.2f}M"
    elif value >= 1_000:
        return f"{value / 1_000:.2f}K"
    else:
        return str(value)


sql_script_help = """
            Jeśli tabela `stocks_data` nie istnieje, zostanie utworzona przy użyciu poniższego skryptu.
            Upewnij się, że **Row Level Security** jest włączone dla tej tabeli w panelu Supabase.

            ```sql
            CREATE TABLE IF NOT EXISTS public.stocks_data (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
                ticker TEXT,
                company TEXT,
                sector TEXT,
                industry TEXT,
                country TEXT,
                market_cap NUMERIC,
                p_e NUMERIC,
                price NUMERIC,
                change NUMERIC,
                volume BIGINT,
                import_date DATE
            );

            ALTER TABLE public.stocks_data ENABLE ROW LEVEL SECURITY;

            CREATE POLICY "Allow public read access"
            ON public.stocks_data FOR SELECT USING (true);

            CREATE POLICY "Allow public insert access"
            ON public.stocks_data FOR INSERT WITH CHECK (true);

            CREATE POLICY "Allow public update access"
            ON public.stocks_data FOR UPDATE USING (true) WITH CHECK (true);

            CREATE POLICY "Allow public delete access"
            ON public.stocks_data FOR DELETE USING (true);
            ```
            """